name: Auto Green

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  auto_green:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit
        run: |
          git config --local user.email "i@mk1.io"
          git config --local user.name "so1ve"
          git add -A

          arr[0]="chore(bot): ğŸ˜‚ auto green"
          arr[1]="chore(bot): ğŸ˜± auto green"
          arr[2]="chore(bot): ğŸ‘¿ auto green"
          arr[3]="chore(bot): ğŸ’© auto green"
          arr[4]="chore(bot): ğŸ™ auto green"
          arr[5]="chore(bot): ğŸ™ˆ auto green"
          arr[6]="chore(bot): ğŸ auto green"
          arr[7]="chore(bot): ğŸ¤– auto green"
          arr[8]="chore(bot): ğŸŸ© auto green"
          arr[9]="chore(bot): ğŸ‘» auto green"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
