name: Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Contribution Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/contribution-snake.svg
            assets/contribution-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: "Generate Contribution Snake"
